/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BrokerageRecord = IDL.Record({
  'id' : IDL.Nat,
  'mcf' : IDL.Text,
  'remark' : IDL.Text,
  'customerName' : IDL.Text,
  'netAmount' : IDL.Opt(IDL.Float64),
  'finance' : IDL.Text,
  'loanAmount' : IDL.Opt(IDL.Float64),
  'createdAt' : IDL.Int,
  'grossAmount' : IDL.Opt(IDL.Float64),
  'brokerageReceivedDate' : IDL.Opt(IDL.Text),
  'serialNumber' : IDL.Nat,
  'bankReceivedDate' : IDL.Opt(IDL.Text),
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(BrokerageRecord)], ['query']),
  'getNextSerialNumber' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecordCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRecordsByRemark' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BrokerageRecord)],
      ['query'],
    ),
  'updateRecord' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BrokerageRecord = IDL.Record({
    'id' : IDL.Nat,
    'mcf' : IDL.Text,
    'remark' : IDL.Text,
    'customerName' : IDL.Text,
    'netAmount' : IDL.Opt(IDL.Float64),
    'finance' : IDL.Text,
    'loanAmount' : IDL.Opt(IDL.Float64),
    'createdAt' : IDL.Int,
    'grossAmount' : IDL.Opt(IDL.Float64),
    'brokerageReceivedDate' : IDL.Opt(IDL.Text),
    'serialNumber' : IDL.Nat,
    'bankReceivedDate' : IDL.Opt(IDL.Text),
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(BrokerageRecord)], ['query']),
    'getNextSerialNumber' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecordCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRecordsByRemark' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BrokerageRecord)],
        ['query'],
      ),
    'updateRecord' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };