/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BrokerageRecord {
    id: bigint;
    mcf: string;
    remark: string;
    customerName: string;
    netAmount?: number;
    finance: string;
    loanAmount?: number;
    createdAt: bigint;
    grossAmount?: number;
    brokerageReceivedDate?: string;
    serialNumber: bigint;
    bankReceivedDate?: string;
    product: string;
}
export interface backendInterface {
    addRecord(finance: string, customerName: string, mcf: string, product: string, grossAmount: number | null, netAmount: number | null, loanAmount: number | null, brokerageReceivedDate: string | null, bankReceivedDate: string | null, remark: string): Promise<bigint>;
    deleteRecord(id: bigint): Promise<boolean>;
    getAllRecords(): Promise<Array<BrokerageRecord>>;
    getNextSerialNumber(): Promise<bigint>;
    getRecordCount(): Promise<bigint>;
    getRecordsByRemark(remark: string): Promise<Array<BrokerageRecord>>;
    updateRecord(id: bigint, finance: string, customerName: string, mcf: string, product: string, grossAmount: number | null, netAmount: number | null, loanAmount: number | null, brokerageReceivedDate: string | null, bankReceivedDate: string | null, remark: string): Promise<boolean>;
}
import type { BrokerageRecord as _BrokerageRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRecord(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number | null, arg5: number | null, arg6: number | null, arg7: string | null, arg8: string | null, arg9: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecord(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecord(arg0, arg1, arg2, arg3, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), arg9);
            return result;
        }
    }
    async deleteRecord(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0);
            return result;
        }
    }
    async getAllRecords(): Promise<Array<BrokerageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecords();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecords();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNextSerialNumber(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextSerialNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextSerialNumber();
            return result;
        }
    }
    async getRecordCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordCount();
            return result;
        }
    }
    async getRecordsByRemark(arg0: string): Promise<Array<BrokerageRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordsByRemark(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordsByRemark(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRecord(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: number | null, arg6: number | null, arg7: number | null, arg8: string | null, arg9: string | null, arg10: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg9), arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg9), arg10);
            return result;
        }
    }
}
function from_candid_BrokerageRecord_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BrokerageRecord): BrokerageRecord {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mcf: string;
    remark: string;
    customerName: string;
    netAmount: [] | [number];
    finance: string;
    loanAmount: [] | [number];
    createdAt: bigint;
    grossAmount: [] | [number];
    brokerageReceivedDate: [] | [string];
    serialNumber: bigint;
    bankReceivedDate: [] | [string];
    product: string;
}): {
    id: bigint;
    mcf: string;
    remark: string;
    customerName: string;
    netAmount?: number;
    finance: string;
    loanAmount?: number;
    createdAt: bigint;
    grossAmount?: number;
    brokerageReceivedDate?: string;
    serialNumber: bigint;
    bankReceivedDate?: string;
    product: string;
} {
    return {
        id: value.id,
        mcf: value.mcf,
        remark: value.remark,
        customerName: value.customerName,
        netAmount: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.netAmount)),
        finance: value.finance,
        loanAmount: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.loanAmount)),
        createdAt: value.createdAt,
        grossAmount: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.grossAmount)),
        brokerageReceivedDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.brokerageReceivedDate)),
        serialNumber: value.serialNumber,
        bankReceivedDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.bankReceivedDate)),
        product: value.product
    };
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BrokerageRecord>): Array<BrokerageRecord> {
    return value.map((x)=>from_candid_BrokerageRecord_n4(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
